# Generated by Django 2.1.3 on 2019-01-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='имя категории')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
        ),
    ]
